# The path of the to obfuscate jar
input = "input.jar"
# The target path for the output jar
output = "output.jar"
# The folder which contains all libraries your program might reference
libraries = "libraries"
# The class file path to use for the loader class
loader = "dev/lennoxlotl/obfuscator"
# The jvm platform to transpile for
# Available are:
#   - hotspot (recommended)
#   - std_java
#   - android
platform = "hotspot"
# Whether to use annotations to filter classes or not
annotations = false
# Deletes the working directory if enabled
delete_temp_dir = true

# Classes and packages to include in obfuscation (if specified, only these will be processed)
# Supports glob patterns like: mypackage/*, mypackage/**/Class1, mypackage/*/Class*
include_patterns = []

# Classes and packages to exclude from obfuscation 
# Supports glob patterns like: mypackage/*, mypackage/**/Class1, mypackage/*/Class*
exclude_patterns = []

# Zig compiler settings
[zig]
# The path to the executable of the compiler
executable = ""
# The amount of threads to use
threads = 32
# The targets to compile the transpiled code for
# Available are:
#   - windows_x86_64
#   - windows_aarch64
#   - linux_x86_64
#   - linux_aarch64
#   - macos_x86_64
#   - macos_aarch64
targets = [
    "windows_x86_64",
    "linux_x86_64"
]